#!/bin/bash

function seq () {
    (( $# >= 1 )) || return 0
    
    local format='%g'
    local separator=$'\n'
    local equal_width=false

    while [[ $1 =~ ^-[^[:digit:]] ]]; do
        if [[ $1 =~ ^(-f|--format=?)(.*) ]]; then
            if [ -n "${BASH_REMATCH[2]}" ]; then
                format=${BASH_REMATCH[2]}
            else
                shift
                format=$1
            fi
        elif [[ $1 =~ ^(-s|--separator=?)(.*) ]]; then
            if [ -n "${BASH_REMATCH[2]}" ]; then
                separator=${BASH_REMATCH[2]}
            else
                shift
                separator=$1
            fi
        elif [[ $1 =~ ^(-w|--equal_width) ]]; then
            equal_width=true
        fi
        shift
    done
    
    local first=1
    local increment=1
    local last
    case $# in
        3)
            last=$3
            increment=$2
            first=$1
        ;;
        2)
            last=$2
            first=$1
        ;;
        1)
            last=$1
        ;;
        *)
            echo "Usage: seq [first [increment]] last" 1>&2
            return 1
        ;;
    esac
    
    if $equal_width; then
        [[ $format =~ %([[:digit:]]*)(.) ]] || { echo "invalid format string: \`$format'" 1>&2; return 1; }
        local first_width=$(printf "%${BASH_REMATCH[2]}" $first)
        local last_width=$(printf "%${BASH_REMATCH[2]}" $last)
        local max_width=$(( ${#first_width} > ${#last_width} ? ${#first_width} : ${#last_width} ))
        format=${format/\%${BASH_REMATCH[1]}?/%0${max_width}${BASH_REMATCH[2]}}
    fi

    local compare
    if (( first <= last )); then
        compare='<='
    else
        compare='>='
    fi
    (( increment $compare 0 )) && return 0

    local i
    for (( i=$first; i $compare last; i=i+increment )); do
        [ "$i" -ne "$first" ] && echo -n "$separator"
        printf "$format" $i
    done
    echo ''
}

seq "$@"
